### PR TITLE
Feature/fix stream test query params

### PR DESCRIPTION
**Pull request by fabiandev**
- Update query params based on selected options
- Disable license field if no DRM system is selected

### CODE REVIEW

**Comment by vzablock** [comment]
Do you have it published on staging?

**Comment by fabiandev** [comment]
> Do you have it published on staging?

Not yet, can deploy it though.

**Comment by fabiandev** [comment]
https://staging.bitmovin.com/demos/stream-test

**Comment by fabiandev** [comment]
It's on staging now.

**Comment by Domysee** [comment]
Please link the issue in the description

**Pull request merged**
